language: php
php:
  - 7.4

git:
  depth: false

notifications:
  email:
    on_success: never

before_install:
  - phpenv config-rm xdebug.ini

jobs:
  include:
    - stage: coverage
      php: 7.4
      name: Test Coverage
      script:
        - composer setup
        - composer build
      after_success:
        - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "medunes"
    token:
      secure: "YlXLPIIqq4qd6IQbiCTwWunwp3KpMB+g4nNhPlYGnd7aWNlN1GM7s/G3um2PNGNjzvVGE131MecM7BGYnz+zVFsyCpLPIzrmnif+Vjs94i0HeXRAdnI9FaIm7/ptxE6ZbU523D+h1rR4DNZKLuYQr0MXy2n1KIMaAmKz9vjV2wfFD4Dp/MhAUdz2ChlL5nyQMi2VMgUaAtRIAEuvWVu1abWGvQN5pEpFYMaaPf7r+Rc19yO7NKW9FmSwdODJJepNbOWwnXyF2Bj1bYKw1nre7fpCL+zaDh/58+QFn1xO24MvQuMwnfnIbBBbRqsg8pyuD/HczhRp3wY+QiQJh8jwv5HrafY+H2UBHPU9KOzrMQDeQLbzNznfHRtncFxl5R2i3kmNNlY2lvnvVGDYl1mCbj3n9kV4J6e4m1jvyj+FhswnLuTbpTZ1Zfmks6GM/a0QmWYIFphSYRvvOcWbFS+jLViUf9TiCVBxSoDp1gUT+rD+PhT7IthfGOpCK2fEGGQQB7BVsv/8ecg8onuzeJpGfZ/inWlADJwEiWEmKcszaFIKhFdwwaR3roiz4LcAY+aMEN2JKQZ/Da06pG3jR6I9UV9XmoFqs3UAPW8aJgLrck8Dc60WrQc2A7TEV+qQzt0yzUWlOOIsnf4pnDCpAxhm30k2Lo7vikx9lAqwGzi/NaA="
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
